### ISSUE TITLE
Datasource to retrieve ldap user

### ISSUE THREAD

**Issue by barryib** [Ouest-France/terraform-provider-ldap#11]
I would like to add a datasource to retrieve a user. I would like to know if we want to let the datasource retrieve any kind of ldap object or just define a specific datasource for user ?

@pablo-ruth any thought ?

**Comment by barryib** [comment]
Never mind, I just noticed that there is a datasource for groups https://github.com/Ouest-France/terraform-provider-ldap/pull/9. So, it make sense to add another datasource for users.

**Comment by pablo-ruth** [comment]
Yes exactly, a new datasource would be best :)

**Comment by pablo-ruth** [comment]
FYI I migrated the provider to TF SDK v2, so if you already started to work on a PR I just wanted to warn you that you'll have to rebase ;)
