### ISSUE TITLE
Documentation does not specify what LDAP schema the provider can work with

### ISSUE THREAD

**Issue by vmnomad** [Ouest-France/terraform-provider-ldap#14]
I can see in the code that "group" objectClass is used when creating Group resource. 
This is common for AD LDAP schema. In the OpenLDAP implementation it could be either "posixGroup" or "groupOfNames", or even both types could be used. Each object class has a different schema and a different set of attributes. For instance, "groupOfNames" cannot be created without members and "posixGroup" requires unique GID. 

Hence, the statement "The LDAP provider is used to interact with any LDAP server." in the documentation is not accurate.

**Comment by pablo-ruth** [comment]
Hi @vmnomad, you're right, I fixed the docs to explicit that it's for AD.
