### ISSUE TITLE
Importing Existing LDAP Groups into state?

### ISSUE THREAD

**Issue by deepbrook** [Ouest-France/terraform-provider-ldap#39]
Hey there,

What exactly is needed to import an existing LDAP group into terraform state using your provider? Would the `ou` string be sufficient?

**Comment by pablo-ruth** [comment]
Hello,
Yes, I need to find out why the docs on master is not updated, but yes you just need the DN of the group: https://github.com/Ouest-France/terraform-provider-ldap/blob/0862f9ccf150b0117064c9c879efa117f1ea6b5e/docs/resources/group.md

**Comment by pablo-ruth** [comment]
I updated the docs: https://registry.terraform.io/providers/Ouest-France/ldap/latest/docs/resources/group#import

**Comment by deepbrook** [comment]
Great! Thank you!
