### ISSUE TITLE
Name is now required when looking for a user in the datasource

### ISSUE THREAD

**Issue by achachw** [Ouest-France/terraform-provider-ldap#41]
Hi @pablo-ruth 
Since the new version of the provider 0.7.4, "Name" is now required when using data ldap_user.
We actually use samAccountName (or user_principal_name) to look for a user, which is more user-friendly to ask 
Is there a reason for that breaking change ?
Thanks

**Comment by pablo-ruth** [comment]
Great, thanks for your review. I merged the PR and releases a v0.7.5 with the fix.
