### ISSUE TITLE
Read "cn" field if "name" does not exist, before giving an error

### ISSUE THREAD

**Issue by dgteixeira** [Ouest-France/terraform-provider-ldap#46]
Hello @pablo-ruth , how are you?

I know this is for AD ldap server, however I was testing this with an openLDAP server.

The problem I'm seeing is getting the group name from the `name` field. Could we check also for the `cn` field?
Here: https://github.com/Ouest-France/terraform-provider-ldap/blob/b6904a590aef6893d8675b61445d97dde34fdc25/ldap/resource_ldap_group.go#L117

Something like this:
```golang
	nameAttr, ok := attributes["name"]
	if !ok || len(nameAttr) != 1 {
                nameAttr, ok := attributes["cn"]
                if !ok || len(nameAttr) != 1 {
			return diag.Errorf("LDAP attribute \"name\" or \"cn\" doesn't exist or is empty for group: %s", dn)
		}
	}

	if err := d.Set("name", nameAttr[0]); err != nil {
		return diag.FromErr(err)
	}
```
I never coded in `go`, so I'm sorry if I'm missing something.

Thanks and best regards!

**Comment by pablo-ruth** [comment]
Hello @dgteixeira,

I tested to launch an openldap server using the Bitnami docker image:
```
docker run --rm -it --name openldap --env LDAP_ADMIN_USERNAME=admin --env LDAP_ADMIN_PASSWORD=adminpassword --env LDAP_USERS=customuser --env LDAP_PASSWORDS=custompassword --env LDAP_GROUP=readers -p 1389:1389 bitnami/openldap:latest
```
In ApacheDirectory I see that there is effectively no `name` attribute but a `cn`.
![image](https://user-images.githubusercontent.com/6660525/159469410-b3bb7102-b225-4061-b61a-5b06fc712c40.png)

After that I tried to create a group with the provider:
```
terraform {
  required_providers {
    ldap = {
      source = "ouest-france/ldap"
    }
  }
  required_version = ">= 0.13"
}


provider "ldap" {
  host          = "127.0.0.1"
  port          = 1389
  tls           = false
  bind_user     = "cn=admin,dc=example,dc=org"
  bind_password = "adminpassword"
}

resource "ldap_group" "group" {
  ou          = "ou=users,dc=example,dc=org"
  name        = "mygroup"
  description = "My group description"
}
```
And I get an error
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # ldap_group.group will be created
  + resource "ldap_group" "group" {
      + description = "My group description"
      + group_type  = (known after apply)
      + id          = (known after apply)
      + name        = "mygroup"
      + ou          = "ou=users,dc=example,dc=org"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ldap_group.group: Creating...
╷
│ Error: LDAP Result Code 21 "Invalid Attribute Syntax": objectClass: value #0 invalid per syntax
│ 
│   with ldap_group.group,
│   on main.tf line 19, in resource "ldap_group" "group":
│   19: resource "ldap_group" "group" {
│ 
```
It seems that there is more than just checking for the `cn` attribute to support openldap, for example the default objectClass for ActiveDirectory is not there on openldap and I see that the membership is under multiple `member` attribute and not `members`...

So I'm sorry, but this provided is really focused on AD and I think it's too specific to support other LDAP servers.

**Comment by dgteixeira** [comment]
Hello @pablo-ruth, thanks a lot for the fast response!

It's okay, I've been trying to use some other providers to see if I can get this to work.
For our use case, we only need `read` permissions, not `write`.
We can close this issue by stating it it's out of scope, i guess!

Thanks again!
