### ISSUE TITLE
Shouldn't we ldap uri instead of host, port, and tls ?

### ISSUE THREAD

**Issue by barryib** [Ouest-France/terraform-provider-ldap#5]
Actually, to use this provider we have to provide: `host`, `port`, `tls` (which is not working) and authentication paramaters. Why not only provide ldap uri ?

Something like this : `ldap://ldap.example.com`, `ldaps://ldap.example.com`, `ldaps://ldap.example.com:8888`.

This will simply inputs and the code.

Furthermore, I want to add ldaps support. So should I rework the provider to use uri or continue and add `tls_insecure`, `tls_ca_certificate` ?

**Comment by pablo-ruth** [comment]
Hi,
I agree it will be better to provide an URI, and go-ldap package already support it via [DialURL func](https://pkg.go.dev/github.com/go-ldap/ldap/v3#DialURL). I still think it's necessary to have a way to disable TLS verification or pass a custom CA, it's very common to have an Internal Org CA on ActiveDirectory. We can use the [DialOpt] arg for DialURL to pass custom TLS config, but we need to upgrade go-ldap dependency to latest version (https://github.com/Ouest-France/goldap/blob/master/go.mod#L5). I'm open to PR :)

**Comment by barryib** [comment]
Oups. I started working on https://github.com/Ouest-France/terraform-provider-ldap/pull/6 without reading your comment.

My bad. Tell me if you still want to use an `uri` instead of `host`, `port`, etc.

**Comment by pablo-ruth** [comment]
No it's ok, we can stay with host/port :+1:
