### ISSUE TITLE
Managed-By attribute support ?

### ISSUE THREAD

**Issue by wNvSp1r1T** [Ouest-France/terraform-provider-ldap#70]
Hello.
Sorry for this question, but is it possibly to set Managed-By attribute with this provider?

**Comment by pablo-ruth** [comment]
Hello,
I'm not sure about how to store this in AD. Do you know a standard ActiveDirectory field that we can use to store this information?

**Comment by wNvSp1r1T** [comment]
@pablo-ruth 
it's AD attribute:
also described there:
https://docs.microsoft.com/en-us/windows/win32/adschema/a-managedby
or there
https://ldapwiki.com/wiki/ManagedBy
