### ISSUE TITLE
duplication of names when creating a group

### ISSUE THREAD

**Issue by IvanTurgenev1** [Ouest-France/terraform-provider-ldap#75]
Sometimes when operator creating or updating a group happens strange things
a duplicate group with a strange name is created:
example of group name:
demo-grrpCNF:1fe3ec62-01a3-48f0-a157-c9e6cf7f3cb3
and when i'm trying to update group members/managedBy error happens

cannot apply: apply failed: LDAP Result Code 68 "Entry Already Exists": 00000526: UpdErr: DSID-031A11DA, problem 6005 (ENTRY_EXISTS), data 0

ldap is loaded and does not work very fast, because of this similar situations arise.
is it possible to somehow bypass this behavior?

**Comment by pablo-ruth** [comment]
Hello @IvanTurgenev1,

Can you give me some informations to debug:
- Terraform version
- Provider version
- Active Directory version

An example of terraform file that reproduce your problem?

Thanks!
