### ISSUE TITLE
Out-of-band group members being removed.

### ISSUE THREAD

**Issue by cmanfre4** [Ouest-France/terraform-provider-ldap#80]
I have a use case where I'd like to be able to create a group and add some default members to it via the `ldap_group` resource, while also being able to add some additional members later via other non-terraform automation.

The problem I'm running into is when the terraform reruns, it will try to remove any of the members that were not originally configured for the `ldap_group` resource.

I saw in issue #43 that a group membership resource is not being considered. Failing that, a boolean argument for the `ldap_group` resource to allow out-of-band members to coexist with explicitly configured members would be helpful e.g. `allow_out_of_band_members`.

Let me know if further details are required and I'll gladly follow up.

**Comment by pablo-ruth** [comment]
Hello @cmanfre4,

You can do that with Terraform syntax. You have to add an ignore_changes lifecycle option to your resource, so at group creation you add your default members, and after that Terraform will not check for changes in the members parameter so it will not remove your additional members add without Terraform:

```
resource "ldap_group" "group" {
  ou      = "OU=Groups,DC=mycompany,DC=local"
  name    = "AdminUsers"
  members = ["CN=MY User,OU=Users,DC=mycompany,DC=local"]

  lifecycle {
    ignore_changes = [members]
  }
}
```

**Comment by cmanfre4** [comment]
@pablo-ruth Thanks for the suggestion! I'll give that a shot.
