### ISSUE TITLE
data source / resources for nested OrganizationUnits

### ISSUE THREAD

**Issue by Markus-** [Ouest-France/terraform-provider-ldap#81]
I want to manage my LDAP-Tree with terraform and for this I have the requirement to create a nested structure like so

OU=top_level_ou,OU=permissions,DC=test,DC=net
|_OU=sub_ou_1,OU=...
   |_CN=group_1
   |_CN=group_2
   |_CN=group_3
|_OU=sub_group_2,OU=...
   |_ ...

So I need to manage the "sub_ou" and the groups.

Is there a possible solution with this provider?

Regards
Markus

**Comment by pablo-ruth** [comment]
Hello @Markus-, I'm out of office I'll check monday !

**Comment by pablo-ruth** [comment]
Hello @Markus-, so if I understand your question, you want to create some OrganizationalUnit with the provider ?

**Comment by Markus-** [comment]
Correct.

**Comment by pablo-ruth** [comment]
Ok, it was not possible, but I just added support to do it. There is a new datasource and resource. I released the version [v0.8.5](https://github.com/Ouest-France/terraform-provider-ldap/releases/tag/v0.8.5) with those new functionalities. I let you test it if you want.

**Comment by Markus-** [comment]
Sorry to ask here again, but it seems that there is a problem with nesting.

If I do it step-wise (for test) it works. But if I proceed I always get the error
```bash
LDAP Result Code 80 "Other": the filter '(objectClass=organizationalUnit)' match more than one OU ...
```

**Comment by pablo-ruth** [comment]
Can you share your terraform code, it will be easier to reproduce ?

**Comment by Markus-** [comment]
main.tf
```bash
resource "ldap_ou" "top_ous" {
  for_each = { for entry in local.top_ous : entry.dn => entry }
  ou          = each.value.ou
  name        = each.value.name
  description = each.value.description
}

resource "ldap_ou" "sub_ous" {
  for_each = { for entry in local.sub_ous : entry.dn => entry }
  ou          = each.value.ou
  name        = each.value.name
  description = each.value.description
}

resource "ldap_group" "cns" {
  for_each = { for entry in local.cns : entry.dn => entry }
  ou          = each.value.ou
  name        = each.value.name
  description = each.value.description
}
```

test.json something like this
```bash
{
    "cn": [
        {
            "dn": "CN=test_prefix_12345_vault_admin,OU=cid_12345_ZABBIX-OS-PLATFORM_INFRA,OU=Customer,OU=TEST,OU=Permissions,DC=example,DC=net",
            "ou": "OU=cid_12345_ZABBIX-OS-PLATFORM_INFRA,OU=Customer,OU=TEST,OU=Permissions,DC=example,DC=net",
            "type": "cn",
            "name": "test_prefix_12345_vault_admin",
            "object_class": "group",
            "description": "TEST Customer Permissions for CID 12345"
        }
    ],
    "sub_ou": [
        {
            "dn": "OU=cid_12345_ZABBIX-OS-PLATFORM_INFRA,OU=Customer,OU=TEST,OU=Permissions,DC=example,DC=net",
            "ou": "OU=Customer,OU=TEST,OU=Permissions,DC=example,DC=net",
            "type": "ou",
            "name": "cid_12345_ZABBIX-OS-PLATFORM_INFRA",
            "object_class": "organizationalUnit",
            "description": "TEST Customer Roles for CID 12345"
        }
    ],
    "top_ou": [
        {
            "dn": "OU=Customer,OU=TEST,OU=Permissions,DC=example,DC=net",
            "ou": "OU=TEST,OU=Permissions,DC=example,DC=net",
            "type": "ou",
            "name": "Customer",
            "object_class": "organizationalUnit",
            "description": "TEST Customers"
        }
    ]
}
```

variables.tf
```
locals {
  top_ous = jsondecode(file("test.json")).top_ou
  sub_ous = jsondecode(file("test.json")).sub_ou
  cns = jsondecode(file("test.json")).cn
}
```

**Comment by Markus-** [comment]
Each level has multiple entries. While "terraform plan" the error occurs

**Comment by pablo-ruth** [comment]
Ok thanks, there was a bug in the code retrieving information about the OU, and in certain cases it can incorrectly find multiple OUs. I fixed the code in [v0.8.6](https://github.com/Ouest-France/terraform-provider-ldap/releases/tag/v0.8.6). Can you try it?

I think you need to also add explicit dependencies between your resources to be sure that top OU are created before sub OU or Group. Something like:
```
resource "ldap_ou" "top_ous" {
  for_each = { for entry in local.top_ous : entry.dn => entry }
  ou          = each.value.ou
  name        = each.value.name
  description = each.value.description
}

resource "ldap_ou" "sub_ous" {
  for_each = { for entry in local.sub_ous : entry.dn => entry }
  ou          = each.value.ou
  name        = each.value.name
  description = each.value.description

  depends_on = [ldap_ou.top_ous]
}

resource "ldap_group" "cns" {
  for_each = { for entry in local.cns : entry.dn => entry }
  ou          = each.value.ou
  name        = each.value.name
  description = each.value.description

  depends_on = [ldap_ou.sub_ous]
}
```

**Comment by Markus-** [comment]
Argh, I used another provider before and deleted the explicit dependencies. But I will try it.

Am 30.01.2023 um 16:50 schrieb Pablo RUTH ***@***.***>:

﻿

Ok thanks, there was a bug in the code retrieving information about the OU, and in certain cases it can incorrectly find multiple OUs. I fixed the code in v0.8.6<https://github.com/Ouest-France/terraform-provider-ldap/releases/tag/v0.8.6>. Can you try it?

I think you need to also add explicit dependencies between your resources to be sure that top OU are created before sub OU or Group. Something like:

resource "ldap_ou" "top_ous" {
  for_each = { for entry in local.top_ous : entry.dn => entry }
  ou          = each.value.ou
  name        = each.value.name
  description = each.value.description
}

resource "ldap_ou" "sub_ous" {
  for_each = { for entry in local.sub_ous : entry.dn => entry }
  ou          = each.value.ou
  name        = each.value.name
  description = each.value.description

  depends_on = [ldap_ou.top_ous]
}

resource "ldap_group" "cns" {
  for_each = { for entry in local.cns : entry.dn => entry }
  ou          = each.value.ou
  name        = each.value.name
  description = each.value.description

  depends_on = [ldap_ou.sub_ous]
}

**Comment by Markus-** [comment]
I just tested it with the explicit depends_on Configuration. Now I can apply / destroy everything as planned.

Thanks. 

Regarding the dependencies I have no better idea than explicitly handle this as stated above. I will have to provide a well sorted json-file with all layers, because I don't think terraform could figure out changes in different levels.

**Comment by Markus-** [comment]
Ok. I can live with it as it works as designed.

Regards
Markus
