### ISSUE TITLE
Creating users?

### ISSUE THREAD

**Issue by olobrian** [Ouest-France/terraform-provider-ldap#93]
Thanks for this provider!

Do you have any plans for supporting creating users? I know it's a bit difficult as I don't think Terraform should handle passwords but I'd imagine the users can be created locked or with a known initial password hash and then be forced to change their password. I'd love to contribute if you think it would be included.

**Comment by pablo-ruth** [comment]
Hello @olobrian,

Yes we are open (ping @mxmorin) to a PR to manage users, but to be sure it's for ActiveDirectory only?
For the password part I think you can read it from the config only on the Create, but don't store it in the state. Password drift will not be detected but I think it's done like this in other providers.
