### ISSUE TITLE
Query the users in the group without extra information

### ISSUE THREAD

**Issue by max1c** [Ouest-France/terraform-provider-ldap#94]
I tried using [ldap_group](https://registry.terraform.io/providers/Ouest-France/ldap/latest/docs/data-sources/group) with `members` attribute and while I get the members list, the format looks like this:
"CN=username,OU=myou,OU=myou2,OU=myou3,OU=myou4,OU=myou5,DC=domain,DC=tld,DC=ltd"

Is there a way to only get usernames without anything else?

**Comment by pablo-ruth** [comment]
hello @max1c, it wasn't possible, so I just added a "members_names" attributes in v0.8.8 (https://registry.terraform.io/providers/Ouest-France/ldap/latest/docs/data-sources/group#members_names).

Can you confirm that's ok for you ?

**Comment by max1c** [comment]
This is perfect! Thank you!
